# Generated by Django 5.0.3 on 2024-05-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodies', '0002_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
