# Generated by Django 5.0.3 on 2024-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodies', '0004_alter_userprofile_address_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='beverage_images/')),
                ('caffeine_content', models.CharField(max_length=100)),
                ('is_carbonated', models.BooleanField(default=False)),
            ],
        ),
    ]
