# Generated by Django 5.0.3 on 2024-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodies', '0005_beverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='caffeine_content',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='is_carbonated',
        ),
        migrations.AlterField(
            model_name='beverage',
            name='image',
            field=models.ImageField(upload_to='beverages/'),
        ),
    ]
